#############################################################################
# Makefile for building: Qtnp
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Jun 24 22:05:10 2012
# Project:  Qtnp.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Qtnp.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtGui -L/usr/lib64 -L/usr/lib64/qt4 -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qtnp.cpp \
		QtnpColorWidget.cpp \
		QtnpImage.cpp \
		QtnpNewFileDialog.cpp \
		QtnpAddGridDialog.cpp \
		QtnpGridAndCoordPlane.cpp \
		fparser/muparser/muParserTokenReader.cpp \
		fparser/muparser/muParserTest.cpp \
		fparser/muparser/muParserInt.cpp \
		fparser/muparser/muParserError.cpp \
		fparser/muparser/muParserDLL.cpp \
		fparser/muparser/muParserCallback.cpp \
		fparser/muparser/muParserBytecode.cpp \
		fparser/muparser/muParserBase.cpp \
		fparser/muparser/muParser.cpp \
		fparser/fparser.cpp \
		QtnpGraphicDialog.cpp \
		QtnpMenuWidget.cpp moc_qtnp.cpp \
		moc_QtnpColorWidget.cpp \
		moc_QtnpImage.cpp \
		moc_QtnpNewFileDialog.cpp \
		moc_QtnpAddGridDialog.cpp \
		moc_QtnpGridAndCoordPlane.cpp \
		moc_QtnpGraphicDialog.cpp \
		moc_QtnpMenuWidget.cpp \
		qrc_res.cpp
OBJECTS       = main.o \
		qtnp.o \
		QtnpColorWidget.o \
		QtnpImage.o \
		QtnpNewFileDialog.o \
		QtnpAddGridDialog.o \
		QtnpGridAndCoordPlane.o \
		muParserTokenReader.o \
		muParserTest.o \
		muParserInt.o \
		muParserError.o \
		muParserDLL.o \
		muParserCallback.o \
		muParserBytecode.o \
		muParserBase.o \
		muParser.o \
		fparser.o \
		QtnpGraphicDialog.o \
		QtnpMenuWidget.o \
		moc_qtnp.o \
		moc_QtnpColorWidget.o \
		moc_QtnpImage.o \
		moc_QtnpNewFileDialog.o \
		moc_QtnpAddGridDialog.o \
		moc_QtnpGridAndCoordPlane.o \
		moc_QtnpGraphicDialog.o \
		moc_QtnpMenuWidget.o \
		qrc_res.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Qtnp.pro
QMAKE_TARGET  = Qtnp
DESTDIR       = 
TARGET        = Qtnp

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_qtnp.h ui_QtnpNewFileDialog.h ui_QtnpAddGridDialog.h ui_QtnpGridAndCoordPlane.h ui_QtnpGraphicDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Qtnp.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtCore.prl
	$(QMAKE) -o Makefile Qtnp.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Qtnp.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Qtnp1.0.0 || $(MKDIR) .tmp/Qtnp1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Qtnp1.0.0/ && $(COPY_FILE) --parents qtnp.h QtnpColorWidget.h QtnpTool.h QtnpImage.h QtnpNewFileDialog.h QtnpAddGridDialog.h QtnpGridAndCoordPlane.h fparser/muparser/muParserTokenReader.h fparser/muparser/muParserToken.h fparser/muparser/muParserTest.h fparser/muparser/muParserTemplateMagic.h fparser/muparser/muParserStack.h fparser/muparser/muParserInt.h fparser/muparser/muParserFixes.h fparser/muparser/muParserError.h fparser/muparser/muParserDLL.h fparser/muparser/muParserDef.h fparser/muparser/muParserCallback.h fparser/muparser/muParserBytecode.h fparser/muparser/muParserBase.h fparser/muparser/muParser.h fparser/fparser.h QtnpGraphicDialog.h QtnpMenuWidget.h .tmp/Qtnp1.0.0/ && $(COPY_FILE) --parents res.qrc .tmp/Qtnp1.0.0/ && $(COPY_FILE) --parents main.cpp qtnp.cpp QtnpColorWidget.cpp QtnpImage.cpp QtnpNewFileDialog.cpp QtnpAddGridDialog.cpp QtnpGridAndCoordPlane.cpp fparser/muparser/muParserTokenReader.cpp fparser/muparser/muParserTest.cpp fparser/muparser/muParserInt.cpp fparser/muparser/muParserError.cpp fparser/muparser/muParserDLL.cpp fparser/muparser/muParserCallback.cpp fparser/muparser/muParserBytecode.cpp fparser/muparser/muParserBase.cpp fparser/muparser/muParser.cpp fparser/fparser.cpp QtnpGraphicDialog.cpp QtnpMenuWidget.cpp .tmp/Qtnp1.0.0/ && $(COPY_FILE) --parents qtnp.ui QtnpNewFileDialog.ui QtnpAddGridDialog.ui QtnpGridAndCoordPlane.ui QtnpGraphicDialog.ui .tmp/Qtnp1.0.0/ && $(COPY_FILE) --parents qtnp_ru.ts qtnp_az.ts qtnp_de.ts qtnp_kz.ts qtnp_be.ts qtnp_en.ts .tmp/Qtnp1.0.0/ && (cd `dirname .tmp/Qtnp1.0.0` && $(TAR) Qtnp1.0.0.tar Qtnp1.0.0 && $(COMPRESS) Qtnp1.0.0.tar) && $(MOVE) `dirname .tmp/Qtnp1.0.0`/Qtnp1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Qtnp1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qtnp.cpp moc_QtnpColorWidget.cpp moc_QtnpImage.cpp moc_QtnpNewFileDialog.cpp moc_QtnpAddGridDialog.cpp moc_QtnpGridAndCoordPlane.cpp moc_QtnpGraphicDialog.cpp moc_QtnpMenuWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qtnp.cpp moc_QtnpColorWidget.cpp moc_QtnpImage.cpp moc_QtnpNewFileDialog.cpp moc_QtnpAddGridDialog.cpp moc_QtnpGridAndCoordPlane.cpp moc_QtnpGraphicDialog.cpp moc_QtnpMenuWidget.cpp
moc_qtnp.cpp: QtnpImage.h \
		QtnpTool.h \
		QtnpColorWidget.h \
		QtnpNewFileDialog.h \
		QtnpGridAndCoordPlane.h \
		QtnpAddGridDialog.h \
		QtnpGraphicDialog.h \
		QtnpMenuWidget.h \
		qtnp.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qtnp.h -o moc_qtnp.cpp

moc_QtnpColorWidget.cpp: QtnpColorWidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QtnpColorWidget.h -o moc_QtnpColorWidget.cpp

moc_QtnpImage.cpp: QtnpTool.h \
		QtnpImage.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QtnpImage.h -o moc_QtnpImage.cpp

moc_QtnpNewFileDialog.cpp: QtnpGridAndCoordPlane.h \
		QtnpColorWidget.h \
		QtnpNewFileDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QtnpNewFileDialog.h -o moc_QtnpNewFileDialog.cpp

moc_QtnpAddGridDialog.cpp: QtnpColorWidget.h \
		QtnpGridAndCoordPlane.h \
		QtnpAddGridDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QtnpAddGridDialog.h -o moc_QtnpAddGridDialog.cpp

moc_QtnpGridAndCoordPlane.cpp: QtnpColorWidget.h \
		QtnpGridAndCoordPlane.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QtnpGridAndCoordPlane.h -o moc_QtnpGridAndCoordPlane.cpp

moc_QtnpGraphicDialog.cpp: QtnpColorWidget.h \
		QtnpGraphicDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QtnpGraphicDialog.h -o moc_QtnpGraphicDialog.cpp

moc_QtnpMenuWidget.cpp: QtnpTool.h \
		QtnpMenuWidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QtnpMenuWidget.h -o moc_QtnpMenuWidget.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		res/fullscreen.png \
		res/open.png \
		res/jogged_ico.png \
		res/graphic.png \
		res/splash.png \
		res/offspring.png \
		res/line.png \
		res/prev.png \
		res/pencil_ico.png \
		res/save.png \
		res/qtnp_ru.qm \
		res/about.png \
		res/save_as.png \
		res/qtnp_en.qm \
		res/grid.png \
		res/line_ico.png \
		res/cursor.png \
		res/new.png \
		res/jogged.png \
		res/template.png \
		res/circle.png \
		res/change_pens_ico.png \
		res/exit.png \
		res/pencil.png
	/usr/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_qtnp.h ui_QtnpNewFileDialog.h ui_QtnpAddGridDialog.h ui_QtnpGridAndCoordPlane.h ui_QtnpGraphicDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_qtnp.h ui_QtnpNewFileDialog.h ui_QtnpAddGridDialog.h ui_QtnpGridAndCoordPlane.h ui_QtnpGraphicDialog.h
ui_qtnp.h: qtnp.ui
	/usr/bin/uic qtnp.ui -o ui_qtnp.h

ui_QtnpNewFileDialog.h: QtnpNewFileDialog.ui
	/usr/bin/uic QtnpNewFileDialog.ui -o ui_QtnpNewFileDialog.h

ui_QtnpAddGridDialog.h: QtnpAddGridDialog.ui
	/usr/bin/uic QtnpAddGridDialog.ui -o ui_QtnpAddGridDialog.h

ui_QtnpGridAndCoordPlane.h: QtnpGridAndCoordPlane.ui
	/usr/bin/uic QtnpGridAndCoordPlane.ui -o ui_QtnpGridAndCoordPlane.h

ui_QtnpGraphicDialog.h: QtnpGraphicDialog.ui
	/usr/bin/uic QtnpGraphicDialog.ui -o ui_QtnpGraphicDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp qtnp.h \
		QtnpImage.h \
		QtnpTool.h \
		QtnpColorWidget.h \
		QtnpNewFileDialog.h \
		QtnpGridAndCoordPlane.h \
		QtnpAddGridDialog.h \
		QtnpGraphicDialog.h \
		QtnpMenuWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qtnp.o: qtnp.cpp qtnp.h \
		QtnpImage.h \
		QtnpTool.h \
		QtnpColorWidget.h \
		QtnpNewFileDialog.h \
		QtnpGridAndCoordPlane.h \
		QtnpAddGridDialog.h \
		QtnpGraphicDialog.h \
		QtnpMenuWidget.h \
		ui_qtnp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtnp.o qtnp.cpp

QtnpColorWidget.o: QtnpColorWidget.cpp QtnpColorWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtnpColorWidget.o QtnpColorWidget.cpp

QtnpImage.o: QtnpImage.cpp QtnpImage.h \
		QtnpTool.h \
		fparser/fparser.h \
		fparser/muparser/muParser.h \
		fparser/muparser/muParserBase.h \
		fparser/muparser/muParserDef.h \
		fparser/muparser/muParserFixes.h \
		fparser/muparser/muParserStack.h \
		fparser/muparser/muParserError.h \
		fparser/muparser/muParserToken.h \
		fparser/muparser/muParserCallback.h \
		fparser/muparser/muParserTokenReader.h \
		fparser/muparser/muParserBytecode.h \
		fparser/muparser/muParserTemplateMagic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtnpImage.o QtnpImage.cpp

QtnpNewFileDialog.o: QtnpNewFileDialog.cpp QtnpNewFileDialog.h \
		QtnpGridAndCoordPlane.h \
		QtnpColorWidget.h \
		ui_QtnpNewFileDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtnpNewFileDialog.o QtnpNewFileDialog.cpp

QtnpAddGridDialog.o: QtnpAddGridDialog.cpp QtnpAddGridDialog.h \
		QtnpColorWidget.h \
		QtnpGridAndCoordPlane.h \
		ui_QtnpAddGridDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtnpAddGridDialog.o QtnpAddGridDialog.cpp

QtnpGridAndCoordPlane.o: QtnpGridAndCoordPlane.cpp QtnpGridAndCoordPlane.h \
		QtnpColorWidget.h \
		ui_QtnpGridAndCoordPlane.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtnpGridAndCoordPlane.o QtnpGridAndCoordPlane.cpp

muParserTokenReader.o: fparser/muparser/muParserTokenReader.cpp fparser/muparser/muParserTokenReader.h \
		fparser/muparser/muParserDef.h \
		fparser/muparser/muParserFixes.h \
		fparser/muparser/muParserToken.h \
		fparser/muparser/muParserError.h \
		fparser/muparser/muParserCallback.h \
		fparser/muparser/muParserBase.h \
		fparser/muparser/muParserStack.h \
		fparser/muparser/muParserBytecode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o muParserTokenReader.o fparser/muparser/muParserTokenReader.cpp

muParserTest.o: fparser/muparser/muParserTest.cpp fparser/muparser/muParserTest.h \
		fparser/muparser/muParser.h \
		fparser/muparser/muParserBase.h \
		fparser/muparser/muParserDef.h \
		fparser/muparser/muParserFixes.h \
		fparser/muparser/muParserStack.h \
		fparser/muparser/muParserError.h \
		fparser/muparser/muParserToken.h \
		fparser/muparser/muParserCallback.h \
		fparser/muparser/muParserTokenReader.h \
		fparser/muparser/muParserBytecode.h \
		fparser/muparser/muParserTemplateMagic.h \
		fparser/muparser/muParserInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o muParserTest.o fparser/muparser/muParserTest.cpp

muParserInt.o: fparser/muparser/muParserInt.cpp fparser/muparser/muParserInt.h \
		fparser/muparser/muParserBase.h \
		fparser/muparser/muParserDef.h \
		fparser/muparser/muParserFixes.h \
		fparser/muparser/muParserStack.h \
		fparser/muparser/muParserError.h \
		fparser/muparser/muParserToken.h \
		fparser/muparser/muParserCallback.h \
		fparser/muparser/muParserTokenReader.h \
		fparser/muparser/muParserBytecode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o muParserInt.o fparser/muparser/muParserInt.cpp

muParserError.o: fparser/muparser/muParserError.cpp fparser/muparser/muParserError.h \
		fparser/muparser/muParserDef.h \
		fparser/muparser/muParserFixes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o muParserError.o fparser/muparser/muParserError.cpp

muParserDLL.o: fparser/muparser/muParserDLL.cpp fparser/muparser/muParserDLL.h \
		fparser/muparser/muParser.h \
		fparser/muparser/muParserBase.h \
		fparser/muparser/muParserDef.h \
		fparser/muparser/muParserFixes.h \
		fparser/muparser/muParserStack.h \
		fparser/muparser/muParserError.h \
		fparser/muparser/muParserToken.h \
		fparser/muparser/muParserCallback.h \
		fparser/muparser/muParserTokenReader.h \
		fparser/muparser/muParserBytecode.h \
		fparser/muparser/muParserTemplateMagic.h \
		fparser/muparser/muParserInt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o muParserDLL.o fparser/muparser/muParserDLL.cpp

muParserCallback.o: fparser/muparser/muParserCallback.cpp fparser/muparser/muParserCallback.h \
		fparser/muparser/muParserDef.h \
		fparser/muparser/muParserFixes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o muParserCallback.o fparser/muparser/muParserCallback.cpp

muParserBytecode.o: fparser/muparser/muParserBytecode.cpp fparser/muparser/muParserBytecode.h \
		fparser/muparser/muParserDef.h \
		fparser/muparser/muParserFixes.h \
		fparser/muparser/muParserError.h \
		fparser/muparser/muParserToken.h \
		fparser/muparser/muParserCallback.h \
		fparser/muparser/muParserStack.h \
		fparser/muparser/muParserTemplateMagic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o muParserBytecode.o fparser/muparser/muParserBytecode.cpp

muParserBase.o: fparser/muparser/muParserBase.cpp fparser/muparser/muParserBase.h \
		fparser/muparser/muParserDef.h \
		fparser/muparser/muParserFixes.h \
		fparser/muparser/muParserStack.h \
		fparser/muparser/muParserError.h \
		fparser/muparser/muParserToken.h \
		fparser/muparser/muParserCallback.h \
		fparser/muparser/muParserTokenReader.h \
		fparser/muparser/muParserBytecode.h \
		fparser/muparser/muParserTemplateMagic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o muParserBase.o fparser/muparser/muParserBase.cpp

muParser.o: fparser/muparser/muParser.cpp fparser/muparser/muParser.h \
		fparser/muparser/muParserBase.h \
		fparser/muparser/muParserDef.h \
		fparser/muparser/muParserFixes.h \
		fparser/muparser/muParserStack.h \
		fparser/muparser/muParserError.h \
		fparser/muparser/muParserToken.h \
		fparser/muparser/muParserCallback.h \
		fparser/muparser/muParserTokenReader.h \
		fparser/muparser/muParserBytecode.h \
		fparser/muparser/muParserTemplateMagic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o muParser.o fparser/muparser/muParser.cpp

fparser.o: fparser/fparser.cpp fparser/fparser.h \
		fparser/muparser/muParser.h \
		fparser/muparser/muParserBase.h \
		fparser/muparser/muParserDef.h \
		fparser/muparser/muParserFixes.h \
		fparser/muparser/muParserStack.h \
		fparser/muparser/muParserError.h \
		fparser/muparser/muParserToken.h \
		fparser/muparser/muParserCallback.h \
		fparser/muparser/muParserTokenReader.h \
		fparser/muparser/muParserBytecode.h \
		fparser/muparser/muParserTemplateMagic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fparser.o fparser/fparser.cpp

QtnpGraphicDialog.o: QtnpGraphicDialog.cpp QtnpGraphicDialog.h \
		QtnpColorWidget.h \
		ui_QtnpGraphicDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtnpGraphicDialog.o QtnpGraphicDialog.cpp

QtnpMenuWidget.o: QtnpMenuWidget.cpp QtnpMenuWidget.h \
		QtnpTool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtnpMenuWidget.o QtnpMenuWidget.cpp

moc_qtnp.o: moc_qtnp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtnp.o moc_qtnp.cpp

moc_QtnpColorWidget.o: moc_QtnpColorWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtnpColorWidget.o moc_QtnpColorWidget.cpp

moc_QtnpImage.o: moc_QtnpImage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtnpImage.o moc_QtnpImage.cpp

moc_QtnpNewFileDialog.o: moc_QtnpNewFileDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtnpNewFileDialog.o moc_QtnpNewFileDialog.cpp

moc_QtnpAddGridDialog.o: moc_QtnpAddGridDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtnpAddGridDialog.o moc_QtnpAddGridDialog.cpp

moc_QtnpGridAndCoordPlane.o: moc_QtnpGridAndCoordPlane.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtnpGridAndCoordPlane.o moc_QtnpGridAndCoordPlane.cpp

moc_QtnpGraphicDialog.o: moc_QtnpGraphicDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtnpGraphicDialog.o moc_QtnpGraphicDialog.cpp

moc_QtnpMenuWidget.o: moc_QtnpMenuWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtnpMenuWidget.o moc_QtnpMenuWidget.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

